project:
  title: estatistica-descritiva-R-1ed
  type: book
  output-dir: _book
  preview:
    port: 3000
    host: 127.0.0.1
    browser: true
    navigate: true
    
lang: pt-BR

book:
  title: Estatística descritiva (1ed)
  subtitle: Apostilas de aula com exemplos em R
  author:
    -  name: Djuri Vieira
    -  name: Luis Francisco Gómez López
  date: 2023-12-19
  date-format: iso
  output-file: estatistica_descritiva_1ed
  cover-image: images/cover.png
  sharing: [twitter, linkedin, facebook]
  downloads: pdf
  edition: 1
  favicon: images/cover.png
  site-url: https://luifrancgom.github.io/estatistica-descritiva-R-1ed/
  repo-url: https://github.com/luifrancgom/estatistica-descritiva-R-1ed
  repo-branch: main
  issue-url: https://github.com/luifrancgom/estatistica-descritiva-R-1ed/issues
  repo-actions: [source, issue, edit]
  reader-mode: true
  language: pt-BR
  search: 
    location: sidebar
    type: textbox
    limit: 20
  sidebar: 
    logo: images/cover.png
    style: floating
    border: true
    alignment: left
  page-navigation: true
  back-to-top-navigation: true
  page-footer:
    left: |
      <span class="faux-block">[Visualize o código-fonte no {{< fa brands github >}} GitHub]({{< var url.repo >}})</span>
      <span class="faux-block">Conteúdo licenciado sob [{{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}} Creative Commons CC BY 4.0]({{< var url.license >}})</span>
    right: |
      <span class="faux-block">Desenhado com {{< fa heart >}} e {{< fa brain >}} </span>
      <span class="faux-block">Construído com [Quarto]({{< var url.quarto >}})</span>
  chapters:
    - index.qmd
    - preface.qmd
    - part: statistics_and_data.qmd
      chapters: 
        - overview.qmd
        - data.qmd
    - part: data_visualization.qmd
      chapters: 
        - tables.qmd
        - two_dimensional_plots.qmd
    - part: summary_statistics.qmd
      chapters: 
        - central_tendency.qmd
        - position.qmd
        - spread.qmd
        - shape.qmd
    - part: probability.qmd
      chapters: 
        - random_experiment_and_probability_space.qmd
        - interpretations_of_probability.qmd
    - part: random_variables.qmd
      chapters: 
        - discrete_probability_distributions.qmd
        - continuous_probability_distributions.qmd
    - references.qmd
  appendices:
    - getting_started_with_r.qmd
    - naive_set_theory.qmd

bibliography: references/estatistica_descritiva_1ed.bib
cls: references/apa_7ed.csl

format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    css: css/styles.css
  pdf: 
    documentclass: book

editor: visual